export const iconImages = [
  require('../../assets/Icon/Tracker/X.png'),
  require('../../assets/Icon/Pyramid/White/1.png'),
  require('../../assets/Icon/Pyramid/White/2.png'),
  require('../../assets/Icon/Pyramid/White/3.png'),
  require('../../assets/Icon/Pyramid/White/4.png'),
  require('../../assets/Icon/Pyramid/White/5.png'),
  require('../../assets/Icon/Pyramid/White/1.png'),
  require('../../assets/Icon/Pyramid/White/1.png'),
  require('../../assets/Icon/Pyramid/White/1.png'),
  require('../../assets/Icon/Pyramid/White/9.png'),
  require('../../assets/Icon/Pyramid/White/1.png'),
  require('../../assets/Icon/Pyramid/White/1.png'),
  require('../../assets/Icon/Pyramid/White/12.png'),
  require('../../assets/Icon/Pyramid/White/1.png'),
  require('../../assets/Icon/Pyramid/White/1.png'),
  require('../../assets/Icon/Pyramid/White/1.png'),
];
